### ISSUE TITLE
Error on xcode 16.1

### ISSUE THREAD

**Issue by FireLord** [danielsaidi/TagKit#4]
![Screenshot 2024-11-04 at 7 47 24 PM](https://github.com/user-attachments/assets/46479f13-b103-46b5-ab4f-8e0dab550cfd)

**Comment by danielsaidi** [comment]
Hi @FireLord 

Oh, that's...unexpected! Seems like Swift 6 changed this handling in Xcode 16.1.

Thank you for reporting - I'm dialing back to 5.9 until I've had a chance to investigate. I'll release a patch for it.

**Comment by danielsaidi** [comment]
Ok, there's a `0.4.1` out which rolls back to Swift 5.9.

I will close this, and have opened #5 to let us track the work on re-enabling Swift 6 support.
